### ISSUE TITLE
Invalid signature file digest for Manifest main attributes

### ISSUE THREAD

**Issue by DarkIsDude** [ozlerhakan/mongolastic#21]
Hello,

Thanks for this tool.
When I launch `docker run --rm -v /opt/ELASTICSEARCH/mongolastic/test.yaml:/test.yaml ozlerhakan/mongolastic test.yaml`, i have the following error:

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:314)
	at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:268)
	at java.util.jar.JarVerifier.processEntry(JarVerifier.java:316)
	at java.util.jar.JarVerifier.update(JarVerifier.java:228)
	at java.util.jar.JarFile.initializeVerifier(JarFile.java:383)
	at java.util.jar.JarFile.getInputStream(JarFile.java:450)
	at sun.misc.URLClassPath$JarLoader$2.getInputStream(URLClassPath.java:940)
	at sun.misc.Resource.cachedInputStream(Resource.java:77)
	at sun.misc.Resource.getByteBuffer(Resource.java:160)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:454)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```

Can you help me?

Thanks,

**Comment by ozlerhakan** [comment]
Hi @doudou34 ,

Thank you for pointing this out. I look into it now.

**Comment by ozlerhakan** [comment]
Could you pull the latest image again @doudou34 ? It should work now.

**Comment by DarkIsDude** [comment]
@ozlerhakan thanks for your quickly answer! Really.
I can't test right now. I will try Monday and I come back to give you a feedback.
Thanks again.

**Comment by DarkIsDude** [comment]
Yes, that's work! Thanks again and have a good week.
