### ISSUE TITLE
cannot transfer data to elasticsearch 7.4 from mongo

### ISSUE THREAD

**Issue by shiveshsky** [ozlerhakan/mongolastic#33]
Here is my config file
```
misc:
    dindex:
        name: rem
    ctype:
        name: calls
mongo:
    host: localhost
    port: 27017
elastic:
    host: localhost
    port: 9300
    clusterName: elasticsearch
```

I am getting this error in ES console
```
exception caught on transport layer [Netty4TcpChannel{localAddress=/127.0.0.1:9300, remoteAddress=/127.0.0.1:60695}], closing connection
java.lang.IllegalStateException: Received message from unsupported version: [6.1.1] minimal compatible version is: [6.8.0]
	at org.elasticsearch.transport.InboundMessage.ensureVersionCompatibility(InboundMessage.java:137) ~[elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.transport.InboundMessage.access$000(InboundMessage.java:39) ~[elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.transport.InboundMessage$Reader.deserialize(InboundMessage.java:76) ~[elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:116) ~[elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:105) ~[elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:660) [elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:62) [transport-netty4-client-7.3.1.jar:7.3.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [netty-codec-4.1.36.Final.jar:4.1.36.Final]
```

And this while running the jar
```
Exception in thread "main" NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{MBfA6xa-TWicelM-f8GEBQ}{localhost}{127.0.0.1:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245)
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:60)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:360)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:405)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:394)
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1247)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:46)
	at com.kodcu.service.ElasticBulkService.dropDataSet(ElasticBulkService.java:90)
	at com.kodcu.provider.Provider.transfer(Provider.java:21)
	at com.kodcu.main.Mongolastic.proceedService(Mongolastic.java:69)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.kodcu.main.Mongolastic.start(Mongolastic.java:58)
	at com.kodcu.main.Mongolastic.main(Mongolastic.java:35)
```

**Comment by shiveshsky** [comment]
I updated the code and dependencies. Its working fine now, please tell me how can I contribute here.

**Comment by ozlerhakan** [comment]
Hey @shiveshsky ,

Just create a pull request with your changes. here is the guide to do that https://help.github.com/en/articles/creating-a-pull-request :)
