### ISSUE TITLE
NoNodeAvailableException with ES-7.6.2

### ISSUE THREAD

**Issue by tarunz001** [ozlerhakan/mongolastic#38]
Hi Hakan,
I am using Elasticsearch: 7.6.2 
Mongo: 4.2.6

Question: would this plugin work for es version above as well??
2) are es end thrown exception(as mentioned below) and noNodeAvailableException on jar cmd related?
Getting NoNodeAvailable exception:

Exception in thread "main" **NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1**}{oEcebCdiT66XkdKa2jThjw}{192.168.0.102}{192.168.0.102:9300}]]
        at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347)
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245)
        at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:60)
        at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:360)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:405)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:394)
        at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1247)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:46)
        at com.kodcu.service.ElasticBulkService.dropDataSet(ElasticBulkService.java:90)
        at com.kodcu.provider.Provider.transfer(Provider.java:21)
        at com.kodcu.main.Mongolastic.proceedService(Mongolastic.java:69)
        at java.util.Optional.ifPresent(Unknown Source)
        at com.kodcu.main.Mongolastic.start(Mongolastic.java:58)
        at com.kodcu.main.Mongolastic.main(Mongolastic.java:35)

ALso on local ES end:
[WARN ][o.e.t.TcpTransport       ] [703226260L] exception caught on transport layer [Netty4TcpChannel{localAddress=/192.168.0.102:9300, remoteAddress=/192.168.0.102:59135}], closing connection
java.lang.IllegalStateException: **Received message from unsupported version: [6.1.1] minimal compatible version is: [6.8.0]**
        at org.elasticsearch.transport.InboundMessage.ensureVersionCompatibility(InboundMessage.java:152) ~[elasticsearch-7.6.2.jar:7.6.2]

Best Regards,
Tarun

**Comment by ozlerhakan** [comment]
Hi @tarunz001 ,

> would this plugin work for es version above as well?

Currently the plugin is outdated, feel free to make a PR to make this possible
