### ISSUE TITLE
Not Executing  in window cmd

### ISSUE THREAD

**Issue by sachinmkp1** [ozlerhakan/mongolastic#43]
I was trying to transfer the elastic data into mongodb , I tried with your jar mongoelastic.jar with below config file and command. It is not getting executed. Please check and let me know the details if I'm missing anything.

#config.json
---------------------------------------------------------------------------------------------------------------------
{
	"misc": {
		"dindex": {
			"name": "elastictest"
			
		},
		"ctype": {
			"name": "mongotest"
			
		}
	},
	"mongo": {
		"host": "localhost",
		"port": 27017
		
	},
	"elastic": {
		"host": "127.0.0.1",
		"port": 9200
		
	}
}
-------------------------------------------------------------------------------------------------------------------
# Command using to execute it. I am sure the jar and config file is under /user/sachin in window .
C:\Users\sachin>java -jar mongolastic.jar -f config.json

# error getting
2020-11-20 15:50:11,472 main ERROR Unable to invoke factory method in class class org.apache.logging.log4j.core.appender.ConsoleAppender for element Console. java.lang.IllegalStateException: No factory method found for class org.apache.logging.log4j.core.appender.ConsoleAppender
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.findFactoryMethod(PluginBuilder.java:224)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:130)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:952)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:892)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:884)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:508)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:232)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:244)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:545)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:617)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:634)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:229)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:152)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:122)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:43)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
        at com.kodcu.main.Mongolastic.<clinit>(Mongolastic.java:23)

2020-11-20 15:50:11,485 main ERROR Null object returned for Console in Appenders.
2020-11-20 15:50:11,491 main ERROR Unable to locate appender "STDOUT" for logger config "root"

**Comment by nashpb** [comment]
Try using wsl or ubuntu
